# Generated by Django 4.0.5 on 2022-07-11 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.FloatField(default=None, verbose_name='Secuencia')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('controlador', models.IntegerField(default=None, verbose_name='Controlador')),
                ('tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado')),
                ('PV', models.FloatField(default=None, verbose_name='Process Value')),
                ('SV', models.FloatField(default=None, verbose_name='Set Value')),
            ],
            options={
                'verbose_name': 'Alarma',
                'verbose_name_plural': 'Alarmas',
                'db_table': 'Alarmas',
                'ordering': ['secuencia'],
            },
        ),
    ]
