# Generated by Django 4.1 on 2022-09-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alarma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmas',
            name='PV',
            field=models.FloatField(default=0, verbose_name='Process Value'),
        ),
        migrations.AlterField(
            model_name='alarmas',
            name='SV',
            field=models.FloatField(default=0, verbose_name='Set Value'),
        ),
        migrations.AlterField(
            model_name='alarmas',
            name='controlador',
            field=models.IntegerField(default=0, verbose_name='Controlador'),
        ),
        migrations.AlterField(
            model_name='alarmas',
            name='estado',
            field=models.CharField(default='', max_length=150, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='alarmas',
            name='fecha',
            field=models.CharField(default='2022-09-05T15:24:47.746273', max_length=150, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='alarmas',
            name='secuencia',
            field=models.FloatField(default=2, verbose_name='Secuencia'),
        ),
        migrations.AlterField(
            model_name='alarmas',
            name='tipo',
            field=models.CharField(default='', max_length=150, verbose_name='Tipo'),
        ),
    ]
