# Generated by Django 4.1 on 2022-09-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
