# Generated by Django 4.1 on 2022-09-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField(default=None, verbose_name='Secuencia')),
                ('fecha', models.CharField(default='2022-09-05T15:24:47.838272', max_length=200, verbose_name='Fecha')),
                ('PV1', models.FloatField(default=None, verbose_name='Process Value 1')),
                ('SV1', models.FloatField(default=None, verbose_name='Set Value 1')),
                ('OUT1', models.FloatField(default=None, verbose_name='Salida 1')),
                ('P1', models.FloatField(default=None, verbose_name='Valor Proporcional 1')),
                ('I1', models.FloatField(default=None, verbose_name='Valor Integral 1')),
                ('D1', models.FloatField(default=None, verbose_name='Valor Derivativo 1')),
                ('PV2', models.FloatField(default=None, verbose_name='Process Value 2')),
                ('SV2', models.FloatField(default=None, verbose_name='Set Value 2')),
                ('OUT2', models.FloatField(default=None, verbose_name='Salida 2')),
                ('P2', models.FloatField(default=None, verbose_name='Valor Proporcional 2')),
                ('I2', models.FloatField(default=None, verbose_name='Valor Integral 2')),
                ('D2', models.FloatField(default=None, verbose_name='Valor Derivativo 2')),
            ],
            options={
                'verbose_name': 'Registros',
                'verbose_name_plural': 'Registros',
                'db_table': 'Registros',
                'ordering': ['secuencia'],
            },
        ),
    ]
